vdc_host:
  dSUID: 0000000042A8708F29EE543E7693000000
  type: vDChost
  name: Test VDC
  model: vDC Host
  model_uid: vdc-host
  model_version: '1.0'
  vendor_id: KarlKiel
  api_version: '2.0'
vdcs:
  0000000142A8708F29EE543E7693000000:
    dSUID: 0000000142A8708F29EE543E7693000000
    type: vDC
    model: Home Assistant VDC
    model_uid: home-assistant-vdc
    model_version: '1.0'
    vendor_id: KarlKiel
    enumeration: 0
    name: Test VDC
vdsds: {}
